name: Bug Report
description: Report a problem, inconsistency, or error in the NeuroFabric framework or documentation
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the issue or unexpected behavior.
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      placeholder: WHITEPAPER.md, README.md, diagrams, example messages, protocol descriptions, etc.

  - type: textarea
    id: reproduction
    attributes:
      label: Steps or Reasoning
      placeholder: Describe how this issue can be reproduced or the reasoning chain that made you notice the inconsistency.

  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior

  - type: textarea
    id: impact
    attributes:
      label: Impact on the Framework
      placeholder: Does it affect communication protocol, architecture, diagrams, scientific claims, etc.?
