import { Message, AgentMetrics } from "./types";

export function exportToJSON(data: {
  task: string;
  messages: Message[];
  metrics: AgentMetrics[];
  finalAnswer: string;
  timestamp: number;
}) {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `neurofabric-result-${Date.now()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportToMarkdown(data: {
  task: string;
  messages: Message[];
  metrics: AgentMetrics[];
  finalAnswer: string;
  timestamp: number;
}) {
  const totalMetrics = {
    time: data.metrics.reduce((sum, m) => sum + m.processingTime, 0),
    cost: data.metrics.reduce((sum, m) => sum + m.cost, 0),
    tokens: data.metrics.reduce((sum, m) => sum + m.tokens.total, 0),
  };

  const markdown = `# NeuroFabric Analysis Result

**Generated:** ${new Date(data.timestamp).toLocaleString()}

## Task
${data.task}

## Final Answer
${data.finalAnswer}

## Performance Metrics

| Metric | Value |
|--------|-------|
| Total Time | ${(totalMetrics.time / 1000).toFixed(2)}s |
| Total Cost | $${totalMetrics.cost.toFixed(4)} |
| Total Tokens | ${totalMetrics.tokens.toLocaleString()} |
| Processing Rate | ${totalMetrics.time > 0 ? (totalMetrics.tokens / (totalMetrics.time / 1000)).toFixed(1) : '0'} tokens/s |

## Agent Performance

${data.metrics.map(m => `### ${m.agentId}
- **LLM Calls:** ${m.llmCalls}
- **Tokens:** ${m.tokens.total.toLocaleString()} (${m.tokens.prompt.toLocaleString()} prompt + ${m.tokens.completion.toLocaleString()} completion)
- **Cost:** $${m.cost.toFixed(4)}
- **Time:** ${(m.processingTime / 1000).toFixed(2)}s
- **Messages Sent:** ${m.messagesSent}
`).join('\n')}

## Communication Flow

${data.messages.map((msg, i) => `${i + 1}. **${msg.from} → ${msg.to}** (${msg.type})
   ${msg.content}
`).join('\n')}

---
Generated by ANHD-NeuroFabric Cognitive Framework
`;

  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `neurofabric-result-${Date.now()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
